apiVersion: v1
kind: Pod
metadata:
  labels:
    app: juggleflow-pod
  name: juggleflow-pod
spec:
  containers:
    - args:
        - postgres
      env:
        - name: POSTGRES_USER
          value: juggle
        - name: POSTGRES_PASSWORD
          value: cHIn8KdtRPOTcQ5kTGhmgsPfM4/liowYpNHXeHG6Tf0=
        - name: POSTGRES_DB
          value: juggleflow
      image: docker.io/library/postgres:17-alpine
      name: juggleflow-db
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: 2254aa0713f91c6fe825dbd7dcfb8c098fc44d6d585c3d994c62efb5450b4a51-pvc

    - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://localhost:5432/juggleflow
        - name: SPRING_DATASOURCE_USERNAME
          value: juggle
        - name: SPRING_DATASOURCE_PASSWORD
          value: cHIn8KdtRPOTcQ5kTGhmgsPfM4/liowYpNHXeHG6Tf0=
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: validate
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: JWT_SECRET
          value: "9+pa2MKK+ReZcROSNYZF0epL4768Pv7IN3Kz0njHpUKb2kxeCPputW3rnM0Zms4A"
        - name: JWT_EXPIRATION_MS
          value: "900000"
        - name: JWT_REFRESH_EXPIRATION_MS
          value: "604800000"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_APPLICATION_NAME
          value: JuggleFlow
        - name: CORS_ALLOWED_ORIGINS
          value: http://localhost:5173
      image: localhost/juggleflow_backend:latest
      name: juggleflow-backend
      ports:
        - containerPort: 8080
          hostPort: 8080
      securityContext: {}

  volumes:
    - name: 2254aa0713f91c6fe825dbd7dcfb8c098fc44d6d585c3d994c62efb5450b4a51-pvc
      persistentVolumeClaim:
        claimName: 2254aa0713f91c6fe825dbd7dcfb8c098fc44d6d585c3d994c62efb5450b4a51
