apiVersion: v1
kind: Pod
metadata:
  labels:
    app: juggleflow
  name: juggleflow
spec:
  containers:
    - name: juggleflow-db
      image: docker.io/library/postgres:17-alpine
      args:
        - postgres
      env:
        - name: POSTGRES_DB
          value: juggleflow_db
        - name: POSTGRES_USER
          value: juggleflow_user
        - name: POSTGRES_PASSWORD
          value: JuggleFlow2026!
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: juggleflow-pgdata-pvc
        - mountPath: /docker-entrypoint-initdb.d
          name: juggleflow-init-sql

  restartPolicy: Always

  volumes:
    - name: juggleflow-pgdata-pvc
      persistentVolumeClaim:
        claimName: juggleflow-pgdata
    - name: juggleflow-init-sql
      hostPath:
        path: /mnt/c/Users/antoi/Documents/juggleflow/apps/backend/init
        type: Directory
