apiVersion: v1
kind: Secret
metadata:
  name: juggleflow-secrets
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_PASSWORD: "change-me"

  # JWT
  JWT_SECRET: "change-me-please-generate-a-long-secret-32-chars-minimum"

  # Optionnel (si Redis protégé)
  REDIS_PASSWORD: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: juggleflow-backend-env
type: Opaque
stringData:
  # À aligner avec ton domaine frontend (prod) :
  CORS_ALLOWED_ORIGINS: "https://juggleflow.example"

