import type { IconName } from './iconRegistry';

/** Tokens alignés sur la charte graphique JuggleFlow. */
export const JUGGLEFLOW_BRAND = {
  purple: '#8B2BE2',
  magenta: '#C724B1',
  orange: '#FF7A00',
  cyan: '#00B4D8',
  info: '#00B4D8',
  alert: '#FF4D4D',
  success: '#0CC896',
  locked: '#333F68',
  muted: '#5A6480',
  light: '#A0AABF',
  gold: '#FBBF24',
  bronze: '#F59E0B',
  silver: '#94A3B8',
  teacher: '#4068D8',
  admin: '#5B20E6',
} as const;

/** Couleur Tailwind par défaut quand aucune className n'est passée à AppIcon. */
export const ICON_COLOR_CLASS: Partial<Record<IconName, string>> = {
  'level-beginner': 'text-info',
  'level-intermediate': 'text-brand-end',
  'level-advanced': 'text-brand',
  'level-expert': 'text-alert',
  'status-mastered': 'text-[#0CC896]',
  'inline-mastered': 'text-[#0CC896]',
  'status-in-progress': 'text-cta',
  'inline-in-progress': 'text-cta',
  'status-locked': 'text-[#333F68]',
  'rank-bronze': 'text-[#F59E0B]',
  'rank-silver': 'text-[#94A3B8]',
  'rank-gold': 'text-[#FBBF24]',
  'resource-video-1': 'text-info',
  'resource-video-2': 'text-teacher',
  'resource-video-3': 'text-brand',
  'resource-exercise-1': 'text-cta',
  'resource-exercise-2': 'text-brand-end',
  'resource-exercise-3': 'text-brand',
  'tag-popular': 'text-cta',
  'alert-warning': 'text-alert',
  'xp-star': 'text-[#FBBF24]',
  timer: 'text-info',
  'tip-lightbulb': 'text-cta',
  'tip-target': 'text-brand-end',
  brain: 'text-brand-end',
  bell: 'text-brand-end',
  moon: 'text-brand',
  offline: 'text-text-muted',
  search: 'text-info',
  juggler: 'text-brand-end',
  play: 'text-brand',
  pause: 'text-brand-end',
  'guide-book': 'text-[#0CC896]',
  'chart-bar': 'text-info',
  clipboard: 'text-text-secondary',
  'pdf-document': 'text-alert',
  'link-external': 'text-info',
  download: 'text-[#0CC896]',
  'star-filled': 'text-[#FBBF24]',
  'star-outline': 'text-text-muted',
  school: 'text-brand',
  'student-user': 'text-brand-end',
  'teacher-user': 'text-teacher',
  lock: 'text-text-muted',
};
