spring.datasource.url=jdbc:postgresql://localhost:5432/juggleflow_db
spring.datasource.username=juggleflow_user
spring.datasource.password=nathan2010
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=Y8f3kL9pQ2sT7vB1xW4zR6nM8cP0dS5hA3eF7gH9jK2mN4pQ6rT8vX0zB1cD3
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
cors.allowed-origins=http://localhost:5173